-file("lib/darwin/test_helpers.ex", 39).

-module('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated').

-compile([no_auto_import]).

-export(['__info__'/1, f/1]).

-spec '__info__'(attributes |
                 compile |
                 functions |
                 macros |
                 md5 |
                 module |
                 deprecated) -> any().

'__info__'(module) ->
    'Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated';
'__info__'(functions) -> [{f, 1}];
'__info__'(macros) -> [];
'__info__'(Key = attributes) ->
    erlang:get_module_info('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                           Key);
'__info__'(Key = compile) ->
    erlang:get_module_info('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                           Key);
'__info__'(Key = md5) ->
    erlang:get_module_info('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                           Key);
'__info__'(deprecated) -> [].

f(X1_@darwin) ->
    'Elixir.Darwin.Mutator.Rewriters.ClauseRewriterWithoutVariableShadowing':execute_transformed_function_clauses([fun
                                                                                                                       (_@darwin__EKVzUoH6S3URLhxi) ->
                                                                                                                           case
                                                                                                                               _@darwin__EKVzUoH6S3URLhxi
                                                                                                                               of
                                                                                                                               {_@1} ->
                                                                                                                                   {ok,
                                                                                                                                    begin
                                                                                                                                        'Elixir.Darwin.Mutator.Rewriters.ClauseRewriterWithoutVariableShadowing':execute_transformed_case_clauses([fun
                                                                                                                                                                                                                                                       (_@darwin__fiL7cBKPJXMjwtwc) ->
                                                                                                                                                                                                                                                           case
                                                                                                                                                                                                                                                               _@darwin__fiL7cBKPJXMjwtwc
                                                                                                                                                                                                                                                               of
                                                                                                                                                                                                                                                               {{_@darwin__ZpDnIXcrJBWXJaOs,
                                                                                                                                                                                                                                                                 _@2}} ->
                                                                                                                                                                                                                                                                   case
                                                                                                                                                                                                                                                                       try
                                                                                                                                                                                                                                                                           _@darwin__ZpDnIXcrJBWXJaOs
                                                                                                                                                                                                                                                                               ==
                                                                                                                                                                                                                                                                               'Elixir.Darwin.Mutators.Default.AtomMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                            0,
                                                                                                                                                                                                                                                                                                                                            ok)
                                                                                                                                                                                                                                                                       catch
                                                                                                                                                                                                                                                                           error:_ ->
                                                                                                                                                                                                                                                                               false
                                                                                                                                                                                                                                                                       end
                                                                                                                                                                                                                                                                       of
                                                                                                                                                                                                                                                                       true ->
                                                                                                                                                                                                                                                                           {ok,
                                                                                                                                                                                                                                                                            begin
                                                                                                                                                                                                                                                                                'Elixir.Darwin.Mutator.Rewriters.ClauseRewriterWithoutVariableShadowing':execute_transformed_case_clauses([fun
                                                                                                                                                                                                                                                                                                                                                                                               (_@darwin__0xK6xtYJeaJce28y) ->
                                                                                                                                                                                                                                                                                                                                                                                                   case
                                                                                                                                                                                                                                                                                                                                                                                                       _@darwin__0xK6xtYJeaJce28y
                                                                                                                                                                                                                                                                                                                                                                                                       of
                                                                                                                                                                                                                                                                                                                                                                                                       {_@darwin__0vRbXaY9EFH7lGDT} ->
                                                                                                                                                                                                                                                                                                                                                                                                           case
                                                                                                                                                                                                                                                                                                                                                                                                               try
                                                                                                                                                                                                                                                                                                                                                                                                                   _@darwin__0vRbXaY9EFH7lGDT
                                                                                                                                                                                                                                                                                                                                                                                                                       ==
                                                                                                                                                                                                                                                                                                                                                                                                                       'Elixir.Darwin.Mutators.Default.IntegerMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       1)
                                                                                                                                                                                                                                                                                                                                                                                                               catch
                                                                                                                                                                                                                                                                                                                                                                                                                   error:_ ->
                                                                                                                                                                                                                                                                                                                                                                                                                       false
                                                                                                                                                                                                                                                                                                                                                                                                               end
                                                                                                                                                                                                                                                                                                                                                                                                               of
                                                                                                                                                                                                                                                                                                                                                                                                               true ->
                                                                                                                                                                                                                                                                                                                                                                                                                   {ok,
                                                                                                                                                                                                                                                                                                                                                                                                                    begin
                                                                                                                                                                                                                                                                                                                                                                                                                        'Elixir.Darwin.Mutators.Default.AtomMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     one)
                                                                                                                                                                                                                                                                                                                                                                                                                    end};
                                                                                                                                                                                                                                                                                                                                                                                                               false ->
                                                                                                                                                                                                                                                                                                                                                                                                                   error
                                                                                                                                                                                                                                                                                                                                                                                                           end;
                                                                                                                                                                                                                                                                                                                                                                                                       _ ->
                                                                                                                                                                                                                                                                                                                                                                                                           error
                                                                                                                                                                                                                                                                                                                                                                                                   end
                                                                                                                                                                                                                                                                                                                                                                                           end,
                                                                                                                                                                                                                                                                                                                                                                                           fun
                                                                                                                                                                                                                                                                                                                                                                                               (_@darwin__flaPwKEQm1ZxDo8G) ->
                                                                                                                                                                                                                                                                                                                                                                                                   case
                                                                                                                                                                                                                                                                                                                                                                                                       _@darwin__flaPwKEQm1ZxDo8G
                                                                                                                                                                                                                                                                                                                                                                                                       of
                                                                                                                                                                                                                                                                                                                                                                                                       {_@darwin__5QlA9lipHjU5pyGL} ->
                                                                                                                                                                                                                                                                                                                                                                                                           case
                                                                                                                                                                                                                                                                                                                                                                                                               try
                                                                                                                                                                                                                                                                                                                                                                                                                   _@darwin__5QlA9lipHjU5pyGL
                                                                                                                                                                                                                                                                                                                                                                                                                       ==
                                                                                                                                                                                                                                                                                                                                                                                                                       'Elixir.Darwin.Mutators.Default.IntegerMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       2)
                                                                                                                                                                                                                                                                                                                                                                                                               catch
                                                                                                                                                                                                                                                                                                                                                                                                                   error:_ ->
                                                                                                                                                                                                                                                                                                                                                                                                                       false
                                                                                                                                                                                                                                                                                                                                                                                                               end
                                                                                                                                                                                                                                                                                                                                                                                                               of
                                                                                                                                                                                                                                                                                                                                                                                                               true ->
                                                                                                                                                                                                                                                                                                                                                                                                                   {ok,
                                                                                                                                                                                                                                                                                                                                                                                                                    begin
                                                                                                                                                                                                                                                                                                                                                                                                                        'Elixir.Darwin.Mutators.Default.AtomMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     two)
                                                                                                                                                                                                                                                                                                                                                                                                                    end};
                                                                                                                                                                                                                                                                                                                                                                                                               false ->
                                                                                                                                                                                                                                                                                                                                                                                                                   error
                                                                                                                                                                                                                                                                                                                                                                                                           end;
                                                                                                                                                                                                                                                                                                                                                                                                       _ ->
                                                                                                                                                                                                                                                                                                                                                                                                           error
                                                                                                                                                                                                                                                                                                                                                                                                   end
                                                                                                                                                                                                                                                                                                                                                                                           end],
                                                                                                                                                                                                                                                                                                                                                                                          {_@2})
                                                                                                                                                                                                                                                                            end};
                                                                                                                                                                                                                                                                       false ->
                                                                                                                                                                                                                                                                           error
                                                                                                                                                                                                                                                                   end;
                                                                                                                                                                                                                                                               _ ->
                                                                                                                                                                                                                                                                   error
                                                                                                                                                                                                                                                           end
                                                                                                                                                                                                                                                   end,
                                                                                                                                                                                                                                                   fun
                                                                                                                                                                                                                                                       (_@darwin__pBqd2LQdtXKoILzs) ->
                                                                                                                                                                                                                                                           case
                                                                                                                                                                                                                                                               _@darwin__pBqd2LQdtXKoILzs
                                                                                                                                                                                                                                                               of
                                                                                                                                                                                                                                                               {_@darwin__bCNhIGzluwPoEA7y} ->
                                                                                                                                                                                                                                                                   case
                                                                                                                                                                                                                                                                       try
                                                                                                                                                                                                                                                                           _@darwin__bCNhIGzluwPoEA7y
                                                                                                                                                                                                                                                                               ==
                                                                                                                                                                                                                                                                               'Elixir.Darwin.Mutators.Default.AtomMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                            5,
                                                                                                                                                                                                                                                                                                                                            error)
                                                                                                                                                                                                                                                                       catch
                                                                                                                                                                                                                                                                           error:_ ->
                                                                                                                                                                                                                                                                               false
                                                                                                                                                                                                                                                                       end
                                                                                                                                                                                                                                                                       of
                                                                                                                                                                                                                                                                       true ->
                                                                                                                                                                                                                                                                           {ok,
                                                                                                                                                                                                                                                                            begin
                                                                                                                                                                                                                                                                                'Elixir.Darwin.Mutators.Default.AtomMutator':darwin_was_here('Elixir.Darwin.DefaultMutators.RuntimeTests.CaseTest.E1C2M0.Mutated',
                                                                                                                                                                                                                                                                                                                                             6,
                                                                                                                                                                                                                                                                                                                                             error)
                                                                                                                                                                                                                                                                            end};
                                                                                                                                                                                                                                                                       false ->
                                                                                                                                                                                                                                                                           error
                                                                                                                                                                                                                                                                   end;
                                                                                                                                                                                                                                                               _ ->
                                                                                                                                                                                                                                                                   error
                                                                                                                                                                                                                                                           end
                                                                                                                                                                                                                                                   end],
                                                                                                                                                                                                                                                  {_@1})
                                                                                                                                    end};
                                                                                                                               _ ->
                                                                                                                                   error
                                                                                                                           end
                                                                                                                   end],
                                                                                                                  {X1_@darwin}).
